version: '3.8'

services:
  emqx:
    image: emqx/emqx:latest
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=emqx
      - EMQX_ALLOW_ANONYMOUS=true
      - EMQX_DATABASE_TYPE=postgresql
      - EMQX_DATABASE_HOST=postgres
      - EMQX_DATABASE_PORT=5432
      - EMQX_DATABASE_USERNAME="
      - EMQX_DATABASE_PASSWORD=your_password
      - EMQX_DATABASE_NAME=your_database
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    depends_on:
      - postgres
    volumes:
      - emqx_data:/opt/emqx/data

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  emqx_data:
  postgres_data: